---
title: "heatmap of mean DMC"
author: "Qing Wang"
date: "02/12/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## prepare data

```{r}
pltgr=readRDS('C:/Users/q.wang/OneDrive - Victor Chang/Documents/tuomas/methylation/Project_13012_B/histone/dmcgr_histone_annotate.rds')
pltgr

```
```{r}
plt=as.data.frame(pltgr)
head(plt)

```

```{r}

keep=c('Lcn2', 'Nupr1')
newplt=plt %>% filter(gene_symbol %in% keep) %>% group_by(histone, gene_symbol) %>% summarise(diff=mean(diff))

newplt
```

save Nupr1 and Lcn2
```{r}
#library(dplyr)
#keep=c('Lcn2', 'Nupr1')
#newplt=plt %>% filter(gene_symbol %in% keep)

#library(openxlsx)
#write.xlsx(newplt, file='C:/Users/q.wang/OneDrive - Victor Chang/Documents/tuomas/methylation/Project_13012_B/histone/lcn2_nupr1_histone.xlsx')
```



make it wide
```{r}
library(tidyr)
newplt2=as.data.frame(t(spread(newplt, histone, diff)))


colnames(newplt2)=newplt2[1,]
newplt2=newplt2[-1,]

order=c('H3k4me1', 'H3K27ac', 'H3k4me3H3K27ac', 'H3k4me1H3K27ac', 'H3k4me1H3k4me3H3K27ac', 'nohistone')
newplt2=newplt2[order,]

newplt2=apply(newplt2, 2, as.numeric)

rownames(newplt2)=order

newplt2
```
heatmap
```{r}
library(ComplexHeatmap)
library(circlize)
library(RColorBrewer)
library(grid)


pdf('lcn2_nupr1_dmc_histone_heatmap.pdf')
Heatmap(newplt2, cluster_columns=FALSE, cluster_rows = F, show_row_names = T, show_column_names = T,  
         column_title = 'DMC differential methylation level', #add column title
         column_names_gp = grid::gpar(fontsize = 12, fontfamily = "sans", fontface = "bold"), #change font size and type
  row_names_gp = grid::gpar(fontsize = 12, fontfamily = "sans", fontface = "bold"),
        width = ncol(newplt2)*unit(5, "mm"),  #change box size
    height = nrow(newplt2)*unit(5, "mm"),
    #column_order=keep[order(de[keep,]$coef, decreasing=T)], 
    border=T, #name = 'Odds Ratio', #column_title =main, #right_annotation = ha, 
        col =colorRamp2(c(min(newplt2, na.rm = T), -0.1), c("blue", "white")) #change order of the color
    )
dev.off()
```

