---
title: "pseudobulk RNA shDNMT1 edgeR "
author: "Qing Wang"
date: "26/9/2023"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## description

read in the count

```{r}
setwd('C:/Users/q.wang/OneDrive - Victor Chang/Documents/tuomas/shDNMT1_scRNA/05pseudobulk/')
count=read.csv('pseudo_count_raw_cluster1_idboth_gfp_positive.csv', row.names = 1)
meta=read.csv('pseudo_meta_cluster1_idboth_gfp_positive.csv', row.names = 1)

head(count)
head(meta)     

rownames(meta)=colnames(count)
colnames(meta)[17]='batch'


meta$batch=ifelse(meta$batch == 'IGO-028755', 'IGO028755',
                  ifelse(meta$batch =='IGO-028756', 'IGO028756', 'IGO028761'))
meta$batch=factor(meta$batch)
str(meta)

```

edgeR pipeline
```{r}
library(edgeR)
y <- DGEList(counts=count,samples=meta)
keep <- filterByExpr(y) 


y <- y[keep,,keep.lib.sizes=FALSE]
summary(keep) #15292
y <- calcNormFactors(y)


nc <- cpm(y, normalized.lib.sizes=TRUE, log=FALSE, prior.count=0.25)
setwd('C:/Users/q.wang/OneDrive - Victor Chang/Documents/tuomas/shDNMT1_scRNA/05pseudobulk/edgeR/cluster1')
write.table(nc, file='edger_normcount_cluster1sample.txt')

design <- model.matrix(~0+both+batch+Sex, y$samples)
design
y <- estimateDisp(y,design)

summary(y$trended.dispersion)

fit <- glmQLFit(y, design, robust=TRUE)#glmQLFit(y, design, robust=TRUE)
summary(fit$var.prior)

``` 

```{r}

cont<- makeContrasts(
  shDNMT1Y_VehY = bothY_shDNMT1 - bothY_control,
  VehA_shDNMT1Y = bothA_control - bothY_shDNMT1, 
  VehA_VehY = bothA_control - bothY_control,
  levels = colnames(design))
cont

aysed <- glmQLFTest(fit, contrast =cont[,'shDNMT1Y_VehY'])
summary(decideTests(aysed))
aysed <- (topTags(aysed, adjust.method = "fdr", n = nrow(count)))
aysed <- aysed$table 
head(aysed)
aysed$gene=rownames(aysed)
setwd('C:/Users/q.wang/OneDrive - Victor Chang/Documents/tuomas/shDNMT1_scRNA/05pseudobulk/edgeR/cluster1')
write.csv(aysed, 'scRNA_DEG_shDNMT1_Y_minus_Veh_Y_edger_gfp_positive.csv')

library(EnhancedVolcano)
EnhancedVolcano(aysed,
                lab = aysed$gene,  
                x = 'logFC',
                pCutoff = 0.05,
                FCcutoff = 0.2,
                #title = "DEG untreated",   
                y = 'PValue',
                xlab = 'log2FC (shDNMT1_Y_minus_Veh_Y)',
                titleLabSize=10,
                subtitleLabSize = 8,
                captionLabSize = 8,
                legendLabSize = 10
)

pdf('scRNA_DEG_shDNMT1_Y_minus_Veh_Y_edger_volcano_gfp_positive.pdf')
EnhancedVolcano(aysed,
                lab = aysed$gene,  
                x = 'logFC',
                pCutoff = 0.05,
                FCcutoff = 0.2,
                #title = "DEG untreated",   
                y = 'PValue',
                xlab = 'log2FC (shDNMT1_Y_minus_Veh_Y)',
                titleLabSize=10,
                subtitleLabSize = 8,
                captionLabSize = 8,
                legendLabSize = 10
)
dev.off()


# VehA_VehY
aysed <- glmQLFTest(fit, contrast =cont[,'VehA_VehY'])
summary(decideTests(aysed))
aysed <- (topTags(aysed, adjust.method = "fdr", n = nrow(count)))
aysed <- aysed$table 
head(aysed)
aysed$gene=rownames(aysed)
write.csv(aysed, 'scRNA_DEG_Veh_A_minus_Veh_Y_edger_gfp_positive.csv')

library(EnhancedVolcano)
EnhancedVolcano(aysed,
                lab = aysed$gene,  
                x = 'logFC',
                pCutoff = 0.05,
                FCcutoff = 0.2,
                #title = "DEG untreated",   
                y = 'PValue',
                xlab = 'log2FC (Veh_A_minus_Veh_Y)',
                titleLabSize=10,
                subtitleLabSize = 8,
                captionLabSize = 8,
                legendLabSize = 10
)

pdf('scRNA_DEG_Veh_A_minus_Veh_Y_edger_volcano_gfp_positive.pdf')
EnhancedVolcano(aysed,
                lab = aysed$gene,  
                x = 'logFC',
                pCutoff = 0.05,
                FCcutoff = 0.2,
                #title = "DEG untreated",   
                y = 'PValue',
                xlab = 'log2FC (Veh_A_minus_Veh_Y)',
                titleLabSize=10,
                subtitleLabSize = 8,
                captionLabSize = 8,
                legendLabSize = 10
)
dev.off()



#VehA_shDNMT1Y
aysed <- glmQLFTest(fit, contrast =cont[,'VehA_shDNMT1Y'])
summary(decideTests(aysed))
aysed <- (topTags(aysed, adjust.method = "fdr", n = nrow(count)))
aysed <- aysed$table 
head(aysed)
aysed$gene=rownames(aysed)
write.csv(aysed, 'scRNA_DEG_VehA_minus_shDNMT1Y_edger_gfp_positive.csv')

pdf('scRNA_DEG_VehA_minus_shDNMT1Y_edger_volcano_gfp_positive.pdf')
EnhancedVolcano(aysed,
                lab = aysed$gene,  
                x = 'logFC',
                pCutoff = 0.05,
                FCcutoff = 0.2,
                #title = "DEG untreated",   
                y = 'PValue',
                xlab = 'log2FC (VehA_minus_shDNMT1Y)',
                titleLabSize=10,
                subtitleLabSize = 8,
                captionLabSize = 8,
                legendLabSize = 10
)
dev.off()


```

```{r}
theme_mytheme <- theme(
  # Specify the overall plot appearance
  plot.background = element_blank(),
  plot.title = element_text(size = 16, face = "bold"),
  plot.subtitle = element_text(size = 14),
  
  # Specify the axis appearance
  axis.text = element_text(size = 12, color = "black"),
  axis.title = element_text(size = 14, color = "black"),
  axis.line = element_line(color = "black", size = 0.5),
  axis.ticks = element_line(color = "black", size = 0.5),
  
  # Specify the legend appearance
  legend.title = element_blank(),
  legend.text = element_text(size = 12),
  legend.position = "right",
  
  # Specify the panel/grid appearance
  panel.background = element_rect(fill = "white", color = "black"),
  panel.grid.major = element_line(color = "lightgray", size = 0.2),
  panel.grid.minor = element_line(color = "lightgray", size = 0.2),
  
  # Specify the plot margins
  plot.margin = margin(1, 1, 1, 1, "cm"),
  
  #set the ratio of the plot 
  aspect.ratio=1
)
```


```{r}
setwd('C:/Users/q.wang/OneDrive - Victor Chang/Documents/tuomas/shDNMT1_scRNA/05pseudobulk/edgeR/cluster1')
nc=read.table(file='edger_normcount_cluster1sample.txt')
colnames(nc)[6]='AP1146 (AP1282).A_control'
head(nc)

nc['Lcn2',]


df=data.frame(norm=as.numeric(nc['Lcn2',]),
              IDboth=colnames(nc))

df

meta=read.csv('C:/Users/q.wang/OneDrive - Victor Chang/Documents/tuomas/shDNMT1_scRNA/05pseudobulk/pseudo_meta_cluster1_idboth_gfp_positive.csv',
               row.names = 1)
head(meta)


library(dplyr)
df=left_join(df, meta, by=c('IDboth'='IDboth'))

head(df)


library(ggplot2)
#ggplot(df, aes(x='both', y='norm'))+geom_boxplot()

pdf('C:/Users/q.wang/OneDrive - Victor Chang/Documents/tuomas/shDNMT1_scRNA/05pseudobulk/edgeR/cluster1/Lcn2_norm_count.pdf')
ggboxplot(df, x='both', y='norm', facet.by = c('X10x.submission.ID'),add = "dotplot")+theme_mytheme+theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

ggboxplot(df, x='both', y='norm', facet.by = c('X10x.submission.ID','Sex'),add = "dotplot")+theme_mytheme+theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
dev.off()
```
```{r}

df=data.frame(norm=as.numeric(nc['Nupr1',]),
              IDboth=colnames(nc))

df

meta=read.csv('C:/Users/q.wang/OneDrive - Victor Chang/Documents/tuomas/shDNMT1_scRNA/05pseudobulk/pseudo_meta_cluster1_idboth_gfp_positive.csv',
               row.names = 1)
head(meta)


library(dplyr)
df=left_join(df, meta, by=c('IDboth'='IDboth'))

head(df)


library(ggplot2)
#ggplot(df, aes(x='both', y='norm'))+geom_boxplot()

pdf('C:/Users/q.wang/OneDrive - Victor Chang/Documents/tuomas/shDNMT1_scRNA/05pseudobulk/edgeR/cluster1/Nupr1_norm_count.pdf')
ggboxplot(df, x='both', y='norm', facet.by = c('X10x.submission.ID'),add = "dotplot")+theme_mytheme+theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

ggboxplot(df, x='both', y='norm', facet.by = c('X10x.submission.ID','Sex'),add = "dotplot")+theme_mytheme+theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
dev.off()
```
```{r}
df=data.frame(norm=as.numeric(nc['Scgb1a1',]),
              IDboth=colnames(nc))

df

meta=read.csv('C:/Users/q.wang/OneDrive - Victor Chang/Documents/tuomas/shDNMT1_scRNA/05pseudobulk/pseudo_meta_cluster1_idboth_gfp_positive.csv',
               row.names = 1)
head(meta)


library(dplyr)
df=left_join(df, meta, by=c('IDboth'='IDboth'))

head(df)


library(ggplot2)
#ggplot(df, aes(x='both', y='norm'))+geom_boxplot()

pdf('C:/Users/q.wang/OneDrive - Victor Chang/Documents/tuomas/shDNMT1_scRNA/05pseudobulk/edgeR/cluster1/Scgb1a1_norm_count.pdf')
ggboxplot(df, x='both', y='norm', facet.by = c('X10x.submission.ID'),add = "dotplot")+theme_mytheme+theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

ggboxplot(df, x='both', y='norm', facet.by = c('X10x.submission.ID','Sex'),add = "dotplot")+theme_mytheme+theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
dev.off()
```

